FROM middagj/kaniko-base

ARG dash_version=0.5.12
ARG dash_checksum=0d632f6b945058d84809cac7805326775bd60cb4a316907d0bd4228ff7107154

# Download
RUN curl -fsSL -o /tmp/dash.tar.xz "https://git.kernel.org/pub/scm/utils/dash/dash.git/snapshot/dash-${dash_version}.tar.gz" \
 && sha256sum -c <<< "${dash_checksum}  /tmp/dash.tar.xz" \
 && tar -xzf /tmp/dash.tar.xz \
 && mv dash-* dash \
 && rm -f /tmp/dash*

# Compile
RUN cd dash \
 && ./autogen.sh \
 && CC='musl-gcc' \
    CFLAGS='-Os -ffunction-sections -fdata-sections' \
    LDFLAGS='-Wl,--gc-sections' \
    ./configure \
 && make

# Install
RUN mv dash/src/dash /busybox/bin

# Clean /busybox
RUN while IFS= read -r file; do \
      strip -s -R .comment -R .gnu.version --strip-unneeded "$file" ; \
    done < <(find -- /busybox/bin -type f | sort)
