FROM middagj/kaniko-base

ARG gnu_mirror=https://ftp.snt.utwente.nl/pub/software/gnu
ARG grep_version=3.11
ARG grep_checksum=1db2aedde89d0dea42b16d9528f894c8d15dae4e190b59aecc78f5a951276eab

# Download
RUN curl -fsSL -o /tmp/grep.tar.xz "${gnu_mirror}/grep/grep-${grep_version}.tar.xz" \
 && sha256sum -c <<< "${grep_checksum}  /tmp/grep.tar.xz" \
 && tar -xJf /tmp/grep.tar.xz \
 && mv grep-* grep \
 && rm -f /tmp/grep*

# Add libraries
COPY --from=middagj/kaniko-pcre /root/include /root/deps/include
COPY --from=middagj/kaniko-pcre /root/lib /root/deps/lib
COPY --from=middagj/kaniko-zlib /root/include /root/deps/include
COPY --from=middagj/kaniko-zlib /root/lib /root/deps/lib

# Compile
RUN cd grep \
 && CC='musl-gcc' \
    CFLAGS="-Os -ffunction-sections -fdata-sections" \
    CPPFLAGS="-I$HOME/deps/include" \
    LDFLAGS="-Wl,--gc-sections -static -L$HOME/deps/lib" \
    ./configure \
 && make

# Install
RUN mv grep/src/*grep /busybox/bin/

# Clean /busybox
RUN for file in /busybox/bin/*; do \
      strip -s -R .comment -R .gnu.version --strip-unneeded $file ; \
    done
