FROM middagj/kaniko-base

ARG gnu_mirror=https://ftp.snt.utwente.nl/pub/software/gnu
ARG coreutils_version=9.5

# Download
RUN curl -fsSL -o /tmp/coreutils.tar.xz "${gnu_mirror}/coreutils/coreutils-${coreutils_version}.tar.xz" \
 && curl -fsSL -o /tmp/coreutils.tar.xz.sig "${gnu_mirror}/coreutils/coreutils-${coreutils_version}.tar.xz.sig" \
 && gpgv --keyring gnu-keyring.gpg /tmp/coreutils.tar.xz.sig /tmp/coreutils.tar.xz \
 && tar -xJf /tmp/coreutils.tar.xz \
 && mv coreutils-* coreutils \
 && rm -f /tmp/coreutils*

# Compile
RUN cd coreutils \
 && FORCE_UNSAFE_CONFIGURE=1 CC='musl-gcc' \
    CFLAGS='-Os -ffunction-sections -fdata-sections' \
    LDFLAGS='-Wl,--gc-sections' \
    ./configure --prefix=/busybox \
 && make

# Install
RUN cd coreutils && make install

# Clean /busybox
RUN for file in /busybox/bin/*; do \
      strip -s -R .comment -R .gnu.version --strip-unneeded $file ; \
    done \
 && rm -rf /busybox/{libexec,share}
