FROM middagj/kaniko-zlib

ARG pcre_version=8.44
ARG pcre_checksum=19108658b23b3ec5058edc9f66ac545ea19f9537234be1ec62b714c84399366d

# Download
RUN curl -fsSL -o /tmp/pcre.tar.bz2 "https://ftp.pcre.org/pub/pcre/pcre-${pcre_version}.tar.bz2" \
 && sha256sum -c <<< "${pcre_checksum}  /tmp/pcre.tar.bz2" \
 && tar -xjf /tmp/pcre.tar.bz2 \
 && mv pcre-* pcre \
 && rm -f /tmp/pcre*

# Compile
RUN cd pcre \
 && CC='musl-gcc' \
    CFLAGS='-Os -ffunction-sections -fdata-sections' \
    LDFLAGS='-Wl,--gc-sections' \
    ./configure --prefix=$HOME \
 && make && make install
