FROM middagj/kaniko-base

ARG gnu_mirror=https://ftp.snt.utwente.nl/pub/software/gnu
ARG findutils_version=4.10.0
ARG findutils_checksum=1387e0b67ff247d2abde998f90dfbf70c1491391a59ddfecb8ae698789f0a4f5

# Download
RUN curl -fsSL -o /tmp/findutils.tar.xz "${gnu_mirror}/findutils/findutils-${findutils_version}.tar.xz" \
 && sha256sum -c <<< "${findutils_checksum}  /tmp/findutils.tar.xz" \
 && tar -xJf /tmp/findutils.tar.xz \
 && mv findutils-* findutils \
 && rm -f /tmp/findutils*

# Compile
RUN cd findutils \
 && CC='musl-gcc' \
    CFLAGS='-Os -ffunction-sections -fdata-sections' \
    LDFLAGS='-Wl,--gc-sections' \
    ./configure \
 && make

# Install
RUN mv findutils/{find/find,xargs/xargs} /busybox/bin/

# Clean /busybox
RUN while IFS= read -r file; do \
      strip -s -R .comment -R .gnu.version --strip-unneeded "$file" ; \
    done < <(find -- /busybox/bin -type f | sort)
