FROM middagj/kaniko-base

ARG gnu_mirror=https://ftp.snt.utwente.nl/pub/software/gnu
ARG bash_version=5.2.37

# Download
RUN curl -fsSL -o /tmp/bash.tar.gz "${gnu_mirror}/bash/bash-${bash_version}.tar.gz" \
 && curl -fsSL -o /tmp/bash.tar.gz.sig "${gnu_mirror}/bash/bash-${bash_version}.tar.gz.sig" \
 && gpgv --keyring gnu-keyring.gpg /tmp/bash.tar.gz.sig /tmp/bash.tar.gz \
 && tar -xzf /tmp/bash.tar.gz \
 && mv bash* bash \
 && rm -f /tmp/bash*

# Compile
RUN cd bash \
 && FORCE_UNSAFE_CONFIGURE=1 \
    CC='musl-gcc' \
    CFLAGS='-Os -ffunction-sections -fdata-sections' \
    LDFLAGS='-Wl,--gc-sections' \
    ./configure --without-bash-malloc \
 && make bash

# Install
RUN mv bash/bash /busybox/bin

# Clean /busybox
RUN for file in /busybox/bin/*; do \
      strip -s -R .comment -R .gnu.version --strip-unneeded $file ; \
    done
