FROM middagj/kaniko-base

ARG gnu_mirror=https://ftp.snt.utwente.nl/pub/software/gnu
ARG make_version=4.4
ARG make_checksum=48d0fc0b2a04bb50f2911c16da65723285f7f4804c74fc5a2124a3df6c5f78c4

# Download
RUN curl -fsSL -o /tmp/make.tar.lz "${gnu_mirror}/make/make-${make_version}.tar.lz" \
 && sha256sum "/tmp/make.tar.lz" \
 && sha256sum -c <<< "${make_checksum}  /tmp/make.tar.lz" \
 && tar -x --lzip -f /tmp/make.tar.lz \
 && mv make-* make \
 && rm -f /tmp/make*

# Compile
RUN cd make \
 && CC='musl-gcc' \
    CFLAGS='-Os -ffunction-sections -fdata-sections' \
    LDFLAGS='-Wl,--gc-sections' \
    ./configure \
 && make

# Install
RUN mv make/make /busybox/bin

# Clean /busybox
RUN for file in /busybox/bin/*; do \
      strip -s -R .comment -R .gnu.version --strip-unneeded $file ; \
    done
