FROM middagj/kaniko-base

ARG gnu_mirror=https://ftp.snt.utwente.nl/pub/software/gnu
ARG ncurses_version=6.5

# Download
RUN curl -fsSL -o /tmp/ncurses.tar.gz "${gnu_mirror}/ncurses/ncurses-${ncurses_version}.tar.gz" \
 && curl -fsSL -o /tmp/ncurses.tar.gz.sig "${gnu_mirror}/ncurses/ncurses-${ncurses_version}.tar.gz.sig" \
 && gpgv --keyring gnu-keyring.gpg /tmp/ncurses.tar.gz.sig /tmp/ncurses.tar.gz \
 && tar -xzf /tmp/ncurses.tar.gz \
 && mv ncurses-* ncurses \
 && rm -f /tmp/ncurses*

# Compile
RUN cd ncurses \
 && CC='musl-gcc' \
    CFLAGS='-Os -ffunction-sections -fdata-sections' \
    LDFLAGS='-Wl,--gc-sections' \
    ./configure --prefix=$HOME --without-cxx --without-tests \
 && make

# Install
RUN cd ncurses && make install
