FROM middagj/kaniko-base

ARG gnu_mirror=https://ftp.snt.utwente.nl/pub/software/gnu
ARG make_version=4.3
ARG make_checksum=de1a441c4edf952521db30bfca80baae86a0ff1acd0a00402999344f04c45e82

# Download
RUN curl -fsSL -o /tmp/make.tar.lz "${gnu_mirror}/make/make-${make_version}.tar.lz" \
 && sha256sum "/tmp/make.tar.lz" \
 && sha256sum -c <<< "${make_checksum}  /tmp/make.tar.lz" \
 && tar -x --lzip -f /tmp/make.tar.lz \
 && mv make-* make \
 && rm -f /tmp/make*

# Compile
RUN cd make \
 && CC='musl-gcc' \
    CFLAGS='-Os -ffunction-sections -fdata-sections' \
    LDFLAGS='-Wl,--gc-sections' \
    ./configure \
 && make

# Install
RUN mv make/make /busybox/bin

# Clean /busybox
RUN while IFS= read -r file; do \
      strip -s -R .comment -R .gnu.version --strip-unneeded "$file" ; \
    done < <(find -- /busybox/bin -type f | sort)
