FROM middagj/kaniko-base

ARG zlib_version=1.3.1
ARG zlib_checksum=38ef96b8dfe510d42707d9c781877914792541133e1870841463bfa73f883e32

# Download
RUN curl -fsSL -o /tmp/zlib.tar.xz "https://zlib.net/zlib-${zlib_version}.tar.xz" \
 && sha256sum -c <<< "${zlib_checksum}  /tmp/zlib.tar.xz" \
 && tar -xJf /tmp/zlib.tar.xz \
 && mv zlib-* zlib \
 && rm -f /tmp/zlib*

# Compile
RUN cd zlib \
 && CC='musl-gcc' \
    CFLAGS='-Os -ffunction-sections -fdata-sections' \
    LDFLAGS='-Wl,--gc-sections' \
    ./configure --prefix=$HOME \
 && make

# Install
RUN cd zlib && make install
