FROM middagj/kaniko-base

ARG gnu_mirror=https://ftp.snt.utwente.nl/pub/software/gnu
ARG sed_version=4.8
ARG sed_checksum=f79b0cfea71b37a8eeec8490db6c5f7ae7719c35587f21edb0617f370eeff633

# Download
RUN curl -fsSL -o /tmp/sed.tar.xz "${gnu_mirror}/sed/sed-${sed_version}.tar.xz" \
 && sha256sum -c <<< "${sed_checksum}  /tmp/sed.tar.xz" \
 && tar -xJf /tmp/sed.tar.xz \
 && mv sed-* sed \
 && rm -f /tmp/sed*

# Compile
RUN cd sed \
 && CC='musl-gcc' \
    CFLAGS="-Os -ffunction-sections -fdata-sections" \
    LDFLAGS="-Wl,--gc-sections -static" \
    ./configure \
 && make

# Install
RUN mv sed/sed/sed /busybox/bin/

# Clean /busybox
RUN while IFS= read -r file; do \
      strip -s -R .comment -R .gnu.version --strip-unneeded "$file" ; \
    done < <(find -- /busybox/bin -type f | sort)
