FROM middagj/kaniko-base

ARG gnu_mirror=https://ftp.snt.utwente.nl/pub/software/gnu
ARG grep_version=3.11

# Download
RUN curl -fsSL -o /tmp/grep.tar.xz "${gnu_mirror}/grep/grep-${grep_version}.tar.xz" \
 && curl -fsSL -o /tmp/grep.tar.xz.sig "${gnu_mirror}/grep/grep-${grep_version}.tar.xz.sig" \
 && gpgv --keyring gnu-keyring.gpg /tmp/grep.tar.xz.sig /tmp/grep.tar.xz \
 && tar -xJf /tmp/grep.tar.xz \
 && mv grep-* grep \
 && rm -f /tmp/grep*

# Add libraries
COPY --from=middagj/kaniko-pcre2 /root/include /root/deps/include
COPY --from=middagj/kaniko-pcre2 /root/lib /root/deps/lib

# Fix pkg-config files
RUN for pc in deps/lib/pkgconfig/*.pc; do sed -i 's#prefix=/root#prefix=/root/deps#' $pc; done

# Compile
RUN cd grep \
 && CC='musl-gcc' \
    CFLAGS="-Os -ffunction-sections -fdata-sections" \
    CPPFLAGS="-I$HOME/deps/include" \
    LDFLAGS="-Wl,--gc-sections -static -L$HOME/deps/lib" \
    PKG_CONFIG_LIBDIR="$HOME/deps/lib/pkgconfig" \
    ./configure \
 && make

# Install
RUN mv grep/src/*grep /busybox/bin/

# Clean /busybox
RUN for file in /busybox/bin/*; do \
      strip -s -R .comment -R .gnu.version --strip-unneeded $file ; \
    done
