FROM middagj/kaniko-base

ARG jq_version=1.7.1
ARG jq_checksum=5942c9b0934e510ee61eb3e30273f1b3fe2590df93933a93d7c58b81d19c8ff5

# Download and install
RUN curl -fsSL -o /busybox/bin/jq "https://github.com/jqlang/jq/releases/download/jq-${jq_version}/jq-linux-amd64" \
 && sha256sum -c <<< "${jq_checksum}  /busybox/bin/jq" \
 && chmod a+x /busybox/bin/jq

# Clean /busybox
RUN for file in /busybox/bin/*; do \
      strip -s -R .comment -R .gnu.version --strip-unneeded $file ; \
    done
