FROM middagj/kaniko-base

ARG gnu_mirror=https://ftp.snt.utwente.nl/pub/software/gnu
ARG findutils_version=4.7.0
ARG findutils_checksum=c5fefbdf9858f7e4feb86f036e1247a54c79fc2d8e4b7064d5aaa1f47dfa789a

# Download
RUN curl -fsSL -o /tmp/findutils.tar.xz "${gnu_mirror}/findutils/findutils-${findutils_version}.tar.xz" \
 && sha256sum -c <<< "${findutils_checksum}  /tmp/findutils.tar.xz" \
 && tar -xJf /tmp/findutils.tar.xz \
 && mv findutils-* findutils \
 && rm -f /tmp/findutils*

# Compile
RUN cd findutils \
 && CC='musl-gcc' \
    CFLAGS='-Os -ffunction-sections -fdata-sections' \
    LDFLAGS='-Wl,--gc-sections' \
    ./configure \
 && make

# Install
RUN mv findutils/{find/find,xargs/xargs} /busybox/bin/

# Clean /busybox
RUN while IFS= read -r file; do \
      strip -s -R .comment -R .gnu.version --strip-unneeded "$file" ; \
    done < <(find -- /busybox/bin -type f | sort)
