FROM middagj/kaniko-base

ARG gnu_mirror=https://ftp.snt.utwente.nl/pub/software/gnu
ARG sed_version=4.9

# Download
RUN curl -fsSL -o /tmp/sed.tar.xz "${gnu_mirror}/sed/sed-${sed_version}.tar.xz" \
 && curl -fsSL -o /tmp/sed.tar.xz.sig "${gnu_mirror}/sed/sed-${sed_version}.tar.xz.sig" \
 && gpgv --keyring gnu-keyring.gpg /tmp/sed.tar.xz.sig /tmp/sed.tar.xz \
 && tar -xJf /tmp/sed.tar.xz \
 && mv sed-* sed \
 && rm -f /tmp/sed*

# Compile
RUN cd sed \
 && CC='musl-gcc' \
    CFLAGS="-Os -ffunction-sections -fdata-sections" \
    LDFLAGS="-Wl,--gc-sections -static" \
    ./configure \
 && make

# Install
RUN mv sed/sed/sed /busybox/bin/

# Clean /busybox
RUN for file in /busybox/bin/*; do \
      strip -s -R .comment -R .gnu.version --strip-unneeded $file ; \
    done
