FROM middagj/kaniko-zlib

ARG pcre_version=8.45
ARG pcre_checksum=4dae6fdcd2bb0bb6c37b5f97c33c2be954da743985369cddac3546e3218bffb8

# Download
RUN curl -fsSL -o /tmp/pcre.tar.bz2 "https://downloads.sourceforge.net/project/pcre/pcre/${pcre_version}/pcre-${pcre_version}.tar.bz2" \
 && sha256sum -c <<< "${pcre_checksum}  /tmp/pcre.tar.bz2" \
 && tar -xjf /tmp/pcre.tar.bz2 \
 && mv pcre-* pcre \
 && rm -f /tmp/pcre*

# Compile
RUN cd pcre \
 && CC='musl-gcc' \
    CFLAGS='-Os -ffunction-sections -fdata-sections' \
    CPPFLAGS="-I$HOME/include" \
    LDFLAGS="-Wl,--gc-sections -L$HOME/lib" \
    ./configure --prefix=$HOME --disable-cpp --enable-jit --enable-utf \
 && make && make install
